---

- name: create/esxifree | Create vmware instances from template
  dseeley.esxifree_guest.esxifree_guest:
    hostname: "{{ cluster_vars.esxi_ip }}"
    username: "{{ cluster_vars.username }}"
    password: "{{ cluster_vars.password }}"
    datastore: "{{ cluster_vars.datastore }}"
    template: "{{ item.image }}"
    name: "{{ item.hostname }}"
    state: present
    hardware:
      version: "{{ cluster_vars.hardware_version }}"
      num_cpus: "{{ item.flavor['num_cpus'] }}"
      memory_mb: "{{ item.flavor['memory_mb'] }}"
      memory_reservation_lock: "{{ item.flavor['memory_reservation_lock'] | default('TRUE') }}"
    annotation:
      Name: "{{item.hostname}}"
      hosttype: "{{item.hosttype}}"
      env: "{{buildenv}}"
      cluster_name: "{{cluster_name}}"
      owner: "{{lookup('env','USER')}}"
      cluster_suffix: "{{cluster_suffix}}"
      regionzone: "{{cluster_vars.region}}-{{item.az_name}}"
      lifecycle_state: "current"
    cloudinit_userdata: "{{ cluster_vars.cloudinit_userdata | default({}) }}"
    delete_cloudinit:  "{{ cluster_vars.delete_cloudinit | default(omit) }}"
    disks: "{{ item.auto_volumes | json_query(\"[].{size_gb: volume_size, type: provisioning_type, volname: volname, src: src }\") | default([]) }}"
    networks: "{{ item.networks | default([]) }}"
    wait: true
  register: esxi_instances
  run_once: true
  with_items: "{{ cluster_hosts_target }}"
  async: 7200
  poll: 0

- name: create/esxifree | Wait for instance creation to complete
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: r__async_status__esxifree_guest
  until: r__async_status__esxifree_guest.finished
  retries: 300
  with_items: "{{ esxi_instances.results }}"

#- name: create/esxifree | r__async_status__esxifree_guest
#  debug: msg={{r__async_status__esxifree_guest}}

- name: create/esxifree | Set a fact containing the newly-created hosts
  set_fact:
    cluster_hosts_created: "{{ r__async_status__esxifree_guest.results | json_query(\"[?changed==`true`].item.item\") }}"
