---

- name: Deploy the cluster
  hosts: localhost
  connection: local
  tasks:
    - { import_role: { name: clusterverse/clean }, tags: [clusterverse_clean], when: clean is defined }       # Alternative include_role (need to force the tags):  - { include_role: { name: clusterverse/clean, apply: {tags: [clusterverse_clean]}}, tags: [clusterverse_clean], when: clean is defined }
    - { import_role: { name: clusterverse/create }, tags: [clusterverse_create] }
    - { import_role: { name: clusterverse/dynamic_inventory }, tags: [clusterverse_dynamic_inventory] }

- name: Configure the cluster
  hosts: all
  tasks:
    - { import_role: { name: clusterverse/config }, tags: [clusterverse_config] }

## Application roles
- name: Application roles
  hosts: all
  tasks:
    - { import_role: { name: "testrole" }, tags: [testrole] }
##

- name: Perform cluster readiness operations
  hosts: localhost
  connection: local
  tasks:
    - { import_role: { name: clusterverse/readiness }, tags: [clusterverse_readiness] }
