---

- name: Redeploy
  hosts: localhost
  tasks:
    - { name: "Get dependent roles via ansible-galaxy", local_action: "command ansible-galaxy role install --ignore-errors -fr requirements.yml", tags: ["always"] }
    - { include_role: { name: 'clusterverse/_dependencies' } }
    - { name: "clusterverse | Copy ansible_ssh_private_key_file", local_action: "copy content={{cluster_vars[buildenv].ssh_connection_cfg.host.ansible_ssh_private_key_file}} dest='id_rsa_ansible_ssh_private_key_file' mode='0600'", when: "cluster_vars[buildenv].ssh_connection_cfg.host.ansible_ssh_private_key_file is defined", no_log: true, tags: ["always"] }
    - { name: "clusterverse | Copy bastion sshkey", local_action: "copy content={{cluster_vars[buildenv].ssh_connection_cfg.bastion.ssh_priv_key}} dest='id_rsa_bastion' mode='0600'", when: "cluster_vars[buildenv].ssh_connection_cfg.bastion.ssh_priv_key is defined", no_log: true, tags: ["always"] }

    - name: redeploy | Run redeploy
      include_role:
        name: clusterverse/redeploy
      vars:
        mainclusteryml: "cluster.yml"
        predeleterole: "testrole/_redeploy"
        redeploy_extra_vars:
          redeploy_var_1: "var_1__val"
          redeploy_var_dict1:
            k1: "var_dict1_val1"
            k2: "var_dict1_val2"
          redeploy_var_list1:
            - "var_list1__elem1"
            - "var_list1__elem2"

- name: redeploy | Application roles
  hosts: all
  tasks:
    - { include_role: { name: "testrole", apply: { tags: ["testrole"]} }, tags: ["testrole"] }
