---

- name: get_cluster_hosts_state/aws | Get existing instance info
  amazon.aws.ec2_instance_info:
    access_key: "{{cluster_vars[buildenv].aws_access_key}}"
    secret_key: "{{cluster_vars[buildenv].aws_secret_key}}"
    session_token: "{{cluster_vars[buildenv].aws_session_token | default(omit)}}"
    endpoint_url: "{{ cluster_vars.aws_endpoint_url | default(omit) }}"
    region: "{{cluster_vars.region}}"
    filters:
      "tag:cluster_name": "{{cluster_name}}"
      "instance-state-name": ["running", "pending", "stopped"]
  register: r__ec2_instance_info
  delegate_to: localhost
  run_once: true

- name: get_cluster_hosts_state/aws | Set cluster_hosts_state
  set_fact:
    cluster_hosts_state: "{{r__ec2_instance_info.instances | json_query(\"[].{name: tags.Name, regionzone: placement.availability_zone, tagslabels: tags, instance_id: instance_id, instance_state: state.name, ipv4: {private: private_ip_address, public: public_ip_address}, disk_info_cloud: block_device_mappings, image: image_id }\") }}"
