---

- name: "Get the state of the {{cluster_vars.type}} VMs in the cluster"
  include_tasks: "get_cluster_hosts_state_{{cluster_vars.type}}.yml"

- name: get_cluster_hosts_state | cluster_hosts_state
  debug: msg="{{cluster_hosts_state}}"
  delegate_to: localhost
  run_once: true
  when: cluster_hosts_state is defined

- name: Set the cluster_suffix based on the existing cluster; if there is no existing cluster, create cluster_suffix anew.  Overridden by command line for some redeploy schemes, e.g. '-e cluster_suffix=1234'
  block:
    - assert: { that: "cluster_suffixes_current | unique | length <= 1", msg: "Multiple 'current' suffixes running ({{cluster_suffixes_current | join(',')}}) - abort" }

    - name: Set cluster_suffix to suffix of current live VMs
      set_fact:
        cluster_suffix: "{{cluster_suffixes_current[0]}}"
      when: cluster_suffixes_current | unique | length==1

    - name: Create new cluster_suffix (epoch time)
      set_fact:
        cluster_suffix: "{{ lookup('pipe', 'date +%s') }}"
      when: cluster_suffixes_current | unique | length==0

    - debug: msg="cluster_suffix = {{cluster_suffix}}"
  vars:
    cluster_suffixes_current: "{{ cluster_hosts_state | json_query(\"[?tagslabels.cv__lifecycle_state=='current'].tagslabels.cv__cluster_suffix\") }}"
