---

- name: Get the state (cluster_hosts_state) of the VMs in the cluster
  include_tasks: get_cluster_hosts_state.yml

- name: Create cluster_hosts_target from the cluster definition in cluster_vars, and add cloud-specific modifications
  include_tasks: get_cluster_hosts_target.yml

