---

- name: Filebeat | Restart and enable filebeat
  become: true
  service:
    name: filebeat
    state: restarted
    enabled: true


- name: Metricbeat | Restart and enable metricbeat
  become: true
  service:
    name: metricbeat
    state: restarted
    enabled: true


- name: Chrony | Restart and enable chrony
  become: true
  service:
    name: chronyd
    state: restarted
    enabled: true