---

- name: Chrony | Restart and enable chrony
  become: true
  command: systemctl is-enabled chronyd
  register: chrony_check
  failed_when: chrony_check.rc not in [0, 1]
  notify: Chrony | Restart and enable chrony - service

- name: Chrony | Restart and enable chrony - service
  become: true
  service:
    name: "{{'chronyd' if chrony_check.rc == 0 else 'chrony'}}"
    state: restarted
    enabled: true
