---

- name: _add_src_diskinfo_to_cluster_hosts_target/aws | cluster_hosts_state
  debug: msg={{cluster_hosts_state}}

- name: _add_src_diskinfo_to_cluster_hosts_target/aws | augment cluster_hosts_target auto_volumes with source disk info
  ansible.builtin.set_fact:
    cluster_hosts_target: |
      {%- set ns = namespace(res=[]) -%}
      {%- for cht_host in cluster_hosts_target -%}
        {%- set vols_ns = namespace(vols=[]) -%}
        {%- for cht_autovol in cht_host.auto_volumes -%}
          {%- set ns_new_autovol = namespace(vol=cht_autovol) -%}
          {%- for chs_host in cluster_hosts_state | selectattr('tagslabels.cv__lifecycle_state', '!=', 'current') -%}
            {%- if cht_host.hostname | regex_replace('-(?!.*-).*') == chs_host.name | regex_replace('-(?!.*-).*') -%}
              {%- for chs_host_diskinfo in chs_host.disk_info_cloud | selectattr('device_name', '==', cht_autovol.device_name) | selectattr('device_name', '!=', '/dev/sda1') -%}
                {%- set ns_new_autovol.vol = ns_new_autovol.vol | combine({ 'src': { 'instance_id': chs_host.instance_id, 'device_name': chs_host_diskinfo.device_name, 'volume_id': chs_host_diskinfo.ebs.volume_id } }) -%}
              {%- endfor -%}
            {%- endif -%}
          {%- endfor -%}
          {%- set vols_ns.vols = vols_ns.vols + [ns_new_autovol.vol] -%}
        {%- endfor -%}
        {%- set new_host = cht_host | combine({'auto_volumes': vols_ns.vols}) -%}
        {%- set ns.res = ns.res + [new_host] -%}
      {%- endfor -%}
      {{ ns.res }}

- name: _add_src_diskinfo_to_cluster_hosts_target/aws | cluster_hosts_target
  debug: msg={{cluster_hosts_target}}
