---

- name: _add_src_diskinfo_to_cluster_hosts_target/gcp | cluster_hosts_state
  debug: msg={{cluster_hosts_state}}

- name: _add_src_diskinfo_to_cluster_hosts_target/gcp | augment cluster_hosts_target auto_volumes with source disk info
  ansible.builtin.set_fact:
    cluster_hosts_target: |
      {%- set ns = namespace(res=[]) -%}
      {%- for cht_host in cluster_hosts_target -%}
        {%- set vols_ns = namespace(vols=[]) -%}
        {%- for cht_autovol in cht_host.auto_volumes -%}
          {%- set ns_new_autovol = namespace(vol=cht_autovol) -%}
          {%- for chs_host in cluster_hosts_state | json_query('[?tagslabels.cv__lifecycle_state != "current"]') -%}
            {%- if cht_host.hostname | regex_replace('-(?!.*-).*') == chs_host.name | regex_replace('-(?!.*-).*') -%}
              {%- for chs_host_diskinfo in chs_host.disk_info_cloud -%}
                {%- if cht_autovol.initialize_params.disk_name | regex_replace('(.*)-.*(--.*)', '\\1\\2') == chs_host_diskinfo.source | basename | regex_replace('(.*)-.*(--.*)', '\\1\\2') -%}
                  {%- ns_new_autovol.vol = ns_new_autovol.vol | combine({
                    'device_name': chs_host_diskinfo.source | basename,
                    'src': { 'hostname': chs_host.name, 'device_name': chs_host_diskinfo.source | basename, 'source_url': chs_host_diskinfo.source },
                    'initialize_params': { 'disk_name': chs_host_diskinfo.source | basename, 'disk_size_gb': chs_host_diskinfo.diskSizeGb }
                  }) -%}
                {%- endif -%}
              {%- endfor -%}
            {%- endif -%}
          {%- endfor -%}
          {%- set vols_ns.vols = vols_ns.vols + [ns_new_autovol.vol] -%}
        {%- endfor -%}
        {%- set new_host = cht_host | combine({'auto_volumes': vols_ns.vols}) -%}
        {%- set ns.res = ns.res + [new_host] -%}
      {%- endfor -%}
      {{ ns.res }}

- name: _add_src_diskinfo_to_cluster_hosts_target/gcp | cluster_hosts_target
  debug: msg={{cluster_hosts_target}}
