---

- name: _add_src_diskinfo_to_cluster_hosts_target/aws | augment cluster_hosts_target auto_volumes with source disk info
  ansible.builtin.set_fact:
    cluster_hosts_target: |
      {%- set ns = namespace(res=[]) -%}
      {%- for cht_host in cluster_hosts_target -%}
        {%- set updated_volumes = [] -%}
        {%- for cht_autovol in cht_host.auto_volumes -%}
          {%- set updated_vol = cht_autovol -%}
          {%- for chs_host in cluster_hosts_state | selectattr('tagslabels.cv__lifecycle_state', '!=', 'current') -%}
            {%- if cht_host.hostname | regex_replace('-(?!.*-).*') == chs_host.name | regex_replace('-(?!.*-).*') -%}
              {%- for chs_host_diskinfo in chs_host.disk_info_cloud | selectattr('device_name', '==', cht_autovol.device_name) | selectattr('device_name', '!=', '/dev/sda1') -%}
                {%- set updated_vol = cht_autovol | combine({ 'src': { 'instance_id': chs_host.instance_id, 'device_name': chs_host_diskinfo.device_name, 'volume_id': chs_host_diskinfo.ebs.volume_id } }) -%}
              {%- endfor -%}
            {%- endif -%}
          {%- endfor -%}
          {%- set updated_volumes = updated_volumes + [updated_vol] -%}
        {%- endfor -%}
        {%- set updated_host = cht_host | combine({'auto_volumes': updated_volumes}) -%}
        {%- set ns.res = ns.res + [updated_host] -%}
      {%- endfor -%}
      {{ ns.res }}

- name: _add_src_diskinfo_to_cluster_hosts_target/aws | cluster_hosts_target
  debug: msg={{cluster_hosts_target}}
