---

- name: _add_src_diskinfo_to_cluster_hosts_target/gcp | augment/update cluster_hosts_target auto_volumes with source disk info
  ansible.builtin.set_fact:
    cluster_hosts_target: |
      {%- set ns = namespace(res=[]) -%}
      {%- for cht_host in cluster_hosts_target -%}
        {%- set updated_volumes = [] -%}
        {%- for cht_autovol in cht_host.auto_volumes -%}
          {%- set updated_vol = cht_autovol -%}
          {%- for chs_host in cluster_hosts_state | json_query('[?tagslabels.cv__lifecycle_state != "current"]') -%}
            {%- if cht_host.hostname | regex_replace('-(?!.*-).*') == chs_host.name | regex_replace('-(?!.*-).*') -%}
              {%- for chs_host_diskinfo in chs_host.disk_info_cloud -%}
                {%- if cht_autovol.initialize_params.disk_name | regex_replace('(.*)-.*(--.*)', '\\1\\2') == chs_host_diskinfo.source | basename | regex_replace('(.*)-.*(--.*)', '\\1\\2') -%}
                  {%- set updated_vol = cht_autovol | combine({
                    'device_name': chs_host_diskinfo.source | basename,
                    'src': { 'hostname': chs_host.name, 'device_name': chs_host_diskinfo.source | basename, 'source_url': chs_host_diskinfo.source },
                    'initialize_params': { 'disk_name': chs_host_diskinfo.source | basename, 'disk_size_gb': chs_host_diskinfo.diskSizeGb }
                  }) -%}
                {%- endif -%}
              {%- endfor -%}
            {%- endif -%}
          {%- endfor -%}
          {%- set updated_volumes = updated_volumes + [updated_vol] -%}
        {%- endfor -%}
        {%- set updated_host = cht_host | combine({'auto_volumes': updated_volumes}) -%}
        {%- set ns.res = ns.res + [updated_host] -%}
      {%- endfor -%}
      {{ ns.res }}

- name: _add_src_diskinfo_to_cluster_hosts_target/gcp | cluster_hosts_target
  debug: msg={{cluster_hosts_target}}
