---

- name: Debug role path
  debug: msg="{{role_path}}"

- name: Test vault-encrypt
  dseeley.ansible_vault_pipe.ansible_vault_pipe:
    plaintext: "hello"
    action: encrypt
  register: r__ansible_vault_encrypt_hello

- debug: msg={{r__ansible_vault_encrypt_hello}}

- name: Test dseeley.tasks_serial
  dseeley.tasks_serial.tasks_serial:
    tasks:
      - name: ansible.builtin.debug
        args:
          msg: "Task 1 - debug (FQCN)!"
      - name: debug
        args:
          msg: "Task 2 - debug!"
      - name: ansible.builtin.shell
        args:
          cmd: echo "Task 3 - shell echo"
      - name: dseeley.ansible_vault_pipe.ansible_vault_pipe
        args:
          vaulttext: "{{r__ansible_vault_encrypt_hello.vaulttext}}"
          action: decrypt
      - name: ansible.builtin.wait_for
        args:
          host: localhost
          port: 22
          timeout: 5
      - name: ansible.builtin.command
        args:
          cmd: "ls -l"

- name: Forcibly fail (-e testfail=fail_3)
  fail:
    msg: testfail=fail_3
  when: testfail is defined and testfail == "fail_3"
