---

- name: config/chrony | Ubuntu install
  become: true
  apt:
    name: chrony
    update_cache: true
    state: present
  when: ansible_os_family == "Debian"

- name: config/chrony | CentOS install
  become: true
  yum:
    name: chrony
    state: present
  when: ansible_os_family == "RedHat"

- name: config/chrony | Configure Chrony
  become: true
  copy:
    dest: "/etc/{% if ansible_os_family == 'Debian'%}chrony/{% endif %}chrony.conf"
    backup: true
    content: |-
      {% for ntp_server in chrony_ntp_servers %}
      server {{ ntp_server }}
      {% endfor %}
      
      {% if ansible_os_family == 'RedHat' %}
      keyfile /etc/chrony.keys
      {% else %}
      keyfile /etc/chrony/chrony.keys
      {% endif %}
      
      driftfile /var/lib/chrony/chrony.drift
      logdir /var/log/chrony
      rtcsync
      makestep 1 3
  notify:
    - config/chrony | Restart and enable chrony
