---

- name: config/libvirt | Remove cloud-init (if cluster_vars.libvirt.delete_cloudinit == true)
  become: true
  apt:
    name: "cloud-init"
    purge: true
    state: absent
  when: cluster_vars.libvirt.delete_cloudinit is defined and cluster_vars.libvirt.delete_cloudinit | bool
