---

- name: config/esxifree | Remove cloud-init (if cluster_vars.esxi.delete_cloudinit == true)
  become: yes
  apt:
    name: "cloud-init"
    purge: yes
    state: absent
  when: cluster_vars.esxi.delete_cloudinit is defined and cluster_vars.esxi.delete_cloudinit | bool
