---

- name: upgrade all packages, reboot and wait (if reboot_on_package_upgrade==true)
  block:
    - name: upgrade all packages (apt - Debian/Ubuntu)
      block:
        - name: install aptitude (needed for the Debian upgrade)
          become: true
          apt:
            update_cache: yes
            name: aptitude
        - name: run apt upgrade
          become: true
          apt:
            upgrade: dist
            force: true
          register: apt_packages_update
      when: ansible_os_family == 'Debian'

    - name: upgrade all packages (yum - RedHat/CentOS)
      become: true
      yum:
        name: "*"
        state: latest
      register: yum_packages_update
      when: ansible_os_family == 'RedHat'

    - name: reboot and wait (if reboot_on_package_upgrade==true)
      become: yes
      reboot:
      when: (reboot_on_package_upgrade is defined and reboot_on_package_upgrade|bool) and (apt_packages_update.changed or yum_packages_update.changed)
  when: pkgupdate is defined and (pkgupdate == 'always' or (pkgupdate == 'onCreate' and inventory_hostname in (hostvars['localhost'].cluster_hosts_created | json_query('[].hostname'))))
