---

- name: prometheus node_exporter | download release archive from github.com
  become: true
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{prometheus_node_exporter_version}}/node_exporter-{{prometheus_node_exporter_version}}.linux-{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}.tar.gz"
    dest: /opt
    remote_src: true

- name: prometheus node_exporter | add node_exporter user
  become: true
  user:
    name: node_exporter
    comment: prometheus node_exporter deamon
    shell: /bin/false
    system: true

- name: prometheus node_exporter | install systemd service file
  become: true
  copy:
    dest: "/etc/systemd/system/prometheus_node_exporter.service"
    content: |-
      [Unit]
      Description=Prometheus Node Exporter

      [Service]
      User=node_exporter
      ExecStart=/opt/node_exporter-{{ prometheus_node_exporter_version }}.linux-{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}/node_exporter --web.listen-address=:{{ prometheus_node_exporter_port }} {{ prometheus_node_exporter_options }}

      [Install]
      WantedBy=default.target

- name: prometheus node_exporter | force systemd to reread configs
  become: true
  systemd: daemon_reload=yes

- name: prometheus node_exporter | enable and start service
  become: true
  service:
    name: prometheus_node_exporter
    state: started
    enabled: True
