---

- name: poweron_vms/aws | hosts_to_start
  debug: msg="{{hosts_to_start}}"

- name: poweron_vms/aws | Power-on VM(s)
  block:
    - name: poweron_vms/aws | Power-on VM(s)
      ec2:
        aws_access_key: "{{cluster_vars[buildenv].aws_access_key}}"
        aws_secret_key: "{{cluster_vars[buildenv].aws_secret_key}}"
        region: "{{ cluster_vars.region }}"
        state: "running"
        instance_ids: "{{ hosts_to_start | json_query(\"[].instance_id\") }}"
        wait: true
      delegate_to: localhost
      run_once: true
  when: hosts_to_start | length