---

- name: poweroff_vms/gcp | hosts_to_stop
  debug: msg="{{hosts_to_stop}}"

- name: poweroff_vms/gcp | Power-off VM(s) and set maintenance_mode=true
  block:
    - name: poweroff_vms/gcp | Power-off VMs asynchronously
      gcp_compute_instance:
        name: "{{item.name}}"
        project: "{{cluster_vars[buildenv].vpc_project_id}}"
        zone: "{{ item.regionzone }}"
        auth_kind: "serviceaccount"
        service_account_file: "{{gcp_credentials_file}}"
        deletion_protection: "{{cluster_vars[buildenv].deletion_protection}}"
        status: "TERMINATED"
        labels: "{{ item.tagslabels | combine({'maintenance_mode': 'true'}) }}"
      with_items: "{{ hosts_to_stop }}"
      register: r__gcp_compute_instance
      async: 7200
      poll: 0

    - name: poweroff_vms/gcp | Wait for VM(s) to power-off
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: async_jobs
      until: async_jobs.finished
      retries: 300
      with_items: "{{r__gcp_compute_instance.results}}"
  when: hosts_to_stop | length