---

- name: "powerchange_vms/aws | hosts_to_powerchange (to {{powerchange_new_state}})"
  debug: msg="{{hosts_to_powerchange}}"

- name: "powerchange_vms/aws | {{powerchange_new_state}} VMs"
  amazon.aws.ec2_instance:
    access_key: "{{cluster_vars[buildenv].aws_access_key}}"
    secret_key: "{{cluster_vars[buildenv].aws_secret_key}}"
    session_token: "{{cluster_vars[buildenv].aws_session_token | default(omit)}}"
    region: "{{ cluster_vars.region }}"
    state: "{% if powerchange_new_state == 'stop' %}stopped{% else %}running{% endif %}"
    instance_ids: "{{ hosts_to_powerchange | json_query(\"[].instance_id\") }}"
  delegate_to: localhost
  run_once: true
  when: hosts_to_powerchange | length
