---

- name: "powerchange_vms/esxifree | hosts_to_powerchange (to {{powerchange_new_state}})"
  debug: msg="{{hosts_to_powerchange}}"

- name: "powerchange_vms/esxifree | {{powerchange_new_state}} VMs"
  dseeley.esxifree_guest.esxifree_guest:
    hostname: "{{ cluster_vars.esxi.esxi_ip }}"
    username: "{{ cluster_vars.esxi.username }}"
    password: "{{ cluster_vars.esxi.password }}"
    name: "{{item.name}}"
    state: "{% if powerchange_new_state == 'stop' %}shutdownguest{% else %}poweredon{% endif %}"
  with_items: "{{ hosts_to_powerchange }}"
  when: hosts_to_powerchange | length > 0
  