---

- name: poweroff_vms/esxifree | hosts_to_stop
  debug: msg="{{hosts_to_stop}}"

- name: poweroff_vms/esxifree | Power-off VM(s) and set maintenance_mode=true
  block:
    - name: poweroff_vms/esxifree | Set maintenance_mode=true
      esxifree_guest:
        hostname: "{{ cluster_vars.esxi_ip }}"
        username: "{{ cluster_vars.username }}"
        password: "{{ cluster_vars.password }}"
        name: "{{item.name}}"
        state: unchanged
        annotation: "{{ item.tagslabels | combine({'maintenance_mode': 'true'}) }}"
      with_items: "{{ hosts_to_stop }}"

    - name: poweroff_vms/esxifree | Power-off VM(s)
      esxifree_guest:
        hostname: "{{ cluster_vars.esxi_ip }}"
        username: "{{ cluster_vars.username }}"
        password: "{{ cluster_vars.password }}"
        name: "{{item.name}}"
        state: shutdownguest
      with_items: "{{ hosts_to_stop }}"
  when: hosts_to_stop | length