---

- debug: msg="Attempting to redeploy {{host_to_del}}"

- name: run predeleterole role
  include_role:
    name: "{{predeleterole}}"
  vars:
    hosts_to_remove: "{{ [host_to_del] }}"
  when: predeleterole is defined and predeleterole != ""

- name: remove dns and host
  block:
    - include_role:
        name: clusterverse/clean
        tasks_from: dns.yml
      when: (hosts_to_clean | length)  and  (cluster_vars.dns_server is defined and cluster_vars.dns_server != "") and (cluster_vars.dns_user_domain is defined and cluster_vars.dns_user_domain != "")

    - include_role:
        name: clusterverse/clean
        tasks_from: "{{cluster_vars.type}}.yml"
      when: (hosts_to_clean | length)
  when: (hosts_to_clean | length)
  vars:
    hosts_to_clean: "{{ [host_to_del] }}"

- name: "Run {{mainclusteryml}} to fix cluster"
  dseeley.nested_playbook.nested_playbook:
    playbook_cmdline: "{{ (argv[1:] | join(' ')) | regex_replace('redeploy.yml', mainclusteryml) }} -e cluster_suffix={{cluster_suffix}} {{ redeploy_extra_vars | extravars_from_dict }}"

- name: re-acquire the dynamic inventory (includes cluster_hosts_state)
  include_role:
    name: clusterverse/dynamic_inventory
