---

- name: readiness | create/update DNS CNAME records
  include_tasks: config_dns_cname.yml
  when: (cluster_vars.dns_server is defined and cluster_vars.dns_server != "") and (cluster_vars.dns_user_domain is defined and cluster_vars.dns_user_domain != "")
