---

- name: readiness | Remove maintenance mode
  include_tasks: "{{ item__include_tasks }}"
  loop: "{{ query('first_found', params) }}"
  loop_control: { loop_var: item__include_tasks }   #This mechanism to include_tasks only when the file exists, also creates a loop iterator 'item' that it sends to the included tasks.  If they also have loops, we get "The loop variable 'item' is already in use" warning.
  vars: { params: { files: ["remove_maintenance_mode_{{cluster_vars.type}}.yml"], skip: true } }

- name: readiness | create/update DNS CNAME records
  include_tasks: config_dns_cname.yml
  when: (cluster_vars.dns_server is defined and cluster_vars.dns_server != "") and (cluster_vars.dns_user_domain is defined and cluster_vars.dns_user_domain != "")
