---

- name: readiness | Remove maintenance mode
  include_tasks: "{{ item }}"
  loop: "{{ query('first_found', params) }}"
  vars: { params: { files: ["remove_maintenance_mode_{{cluster_vars.type}}.yml"], skip: true } }

- name: readiness | create/update DNS CNAME records
  include_tasks: config_dns_cname.yml
  when: (cluster_vars.dns_server is defined and cluster_vars.dns_server != "") and (cluster_vars.dns_user_domain is defined and cluster_vars.dns_user_domain != "")
