---

- name: remove_maintenance_mode/esxifree | Set maintenance_mode to false
  dseeley.esxifree_guest.esxifree_guest:
    hostname: "{{ cluster_vars.esxi.esxi_ip }}"
    username: "{{ cluster_vars.esxi.username }}"
    password: "{{ cluster_vars.esxi.password }}"
    name: "{{item.name}}"
    state: "unchanged"
    annotation: "{{ item.tagslabels | combine({'maintenance_mode': 'false'}) }}"
  with_items: "{{ cluster_hosts_state }}"
