---

- name: remove_maintenance_mode/aws | Set maintenance_mode to false
  amazon.aws.ec2_tag:
    access_key: "{{cluster_vars[buildenv].aws_access_key}}"
    secret_key: "{{cluster_vars[buildenv].aws_secret_key}}"
    session_token: "{{cluster_vars[buildenv].aws_session_token | default(omit)}}"
    region: "{{cluster_vars.region}}"
    resource: "{{ item }}"
    tags:
      maintenance_mode: "false"
  delegate_to: localhost
  run_once: true
  with_items: "{{ cluster_hosts_state | json_query(\"[].instance_id\") }}"
