name: CI for Clusterverse

on:
  push:
    branches:
      - master
      - actions
  pull_request:
    branches:
      - actions
      - master
  workflow_dispatch:  # Allows manual triggering


jobs:
  vault-check:
    name: Validate Vault-Encrypted Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Copy vault password script
        run: |
          cp .vaultpass-client.py .github/vaultpass-client.py

      - name: Test vault decryption
        env:
          VAULT_PASSWORD_BUILDENV: ${{ secrets.VAULT_PASSWORD }}
        run: |
          ansible-vault decrypt --vault-id=sandbox@.github/vaultpass-client.py roles/clusterverse/tests/test_vault.yml